export const LOGIN_REQUISICAO = 'LOGIN_REQUISICAO';
export const LOGIN_SUCESSO = 'LOGIN_SUCESSO';
export const LOGIN_FALHA = 'LOGIN_FALHA';
export const LOGOUT = 'LOGOUT';
export const REGISTRAR_REQUISICAO = 'REGISTRAR_REQUISICAO';
export const REGISTRAR_SUCESSO = 'REGISTRAR_SUCESSO';
export const REGISTRAR_FALHA = 'REGISTRAR_FALHA';
export const DEFINIR_INFORMACOES_CONTA = 'DEFINIR_INFORMACOES_CONTA';
