export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_CLIENT_CONNECTEDUSERS = 'SOCKET_CLIENT_CONNECTEDUSERS';
export const SOCKET_CLIENT_ENTRAREMSALA = 'SOCKET_CLIENT_ENTRAREMSALA';
export const SOCKET_CLIENT_SAIRDASALA = 'SOCKET_CLIENT_SAIRDASALA';
