describe('Testando Tela Inicial', function() {
    it('Visita Tela inicial', function() {
        cy.visit('http://localhost:8080/login')
    })
    it('Utiliza env Variable', function() {
        cy.visit('http://' + Cypress.env('VUE_APP_HOST') + ':' + Cypress.env('VUE_APP_PORT') + '/login')
    })
    it('Faz Login', function() {
        // cy.visit('http://' + Cypress.env('VUE_APP_HOST') + ':' + Cypress.env('VUE_APP_PORT') + '/login')
        cy.get('[name="email"]')
            .type('abcd@gmail.com')
        cy.wait(1000)
        cy.get('[name="password"]')
            .type('123456')
        cy.wait(1000)
        cy.get('.v-btn').click()
    })
    it('Cria Notificacao', function() {
        cy.wait(1000)
        cy.get('.v-toolbar__side-icon > .v-btn__content > .v-icon').click()
        cy.wait(1000)
        cy.get('.pt-0 > :nth-child(3) > .v-list__tile').click()
        cy.wait(1000)
        cy.get('.v-btn--bottom').click()
        cy.wait(1000)
        cy.get('textarea').type('[{{}cod_grupo: 1234, pronac: 123456}]')
        cy.wait(1000)
        cy.get('.xs12 > .v-select > .v-input__control > .v-input__slot > .v-select__slot > .v-select__selections').click()
        cy.wait(2000)
        cy.get('.v-menu__content--fixed > .v-select-list > .v-list > :nth-child(1) > .v-list__tile > .v-list__tile__content').click()
        cy.get('.blue > .v-btn__content').click()
        // cy.visit('http://' + Cypress.env('VUE_APP_HOST') + ':' + Cypress.env('VUE_APP_PORT') + '/notificacao')
    })
})
