export const OBTER_SISTEMAS = 'OBTER_SISTEMAS';
export const REMOVER_SISTEMA = 'REMOVER_SISTEMA';
export const ATUALIZAR_SISTEMA = 'ATUALIZAR_SISTEMA';
export const ACRESCENTAR_SISTEMA = 'ACRESCENTAR_SISTEMA';
